@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Dec 20 19:21:52 -0800 2020
REM SW Build 2960000 on Wed Aug  5 22:57:20 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim EE214_Proj9Req1_TB_behav -key {Behavioral:sim_1:Functional:EE214_Proj9Req1_TB} -tclbatch EE214_Proj9Req1_TB.tcl -log simulate.log"
call xsim  EE214_Proj9Req1_TB_behav -key {Behavioral:sim_1:Functional:EE214_Proj9Req1_TB} -tclbatch EE214_Proj9Req1_TB.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
