@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Oct 15 19:29:13 -0700 2020
REM SW Build 2960000 on Wed Aug  5 22:57:20 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 1b17fa34d58e4147a7fb2ca234b391e6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot EE214_proj4Req1_muxDemuxWrapper_test_fixture_behav xil_defaultlib.EE214_proj4Req1_muxDemuxWrapper_test_fixture xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 1b17fa34d58e4147a7fb2ca234b391e6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot EE214_proj4Req1_muxDemuxWrapper_test_fixture_behav xil_defaultlib.EE214_proj4Req1_muxDemuxWrapper_test_fixture xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
